const router = require('express').Router();
const controller = require('../controllers/authController');
const { requireAuth } = require('../middleware/auth');
router.post('/register', controller.register);
router.post('/login', controller.login);
router.post('/google', controller.googleLogin);
router.post('/forgot-password', controller.forgotPassword);
router.post('/reset-password', controller.resetPassword);
router.get('/me', requireAuth, controller.me);
router.post('/logout', requireAuth, controller.logout);
module.exports = router;
